# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SJIm_pyfqpgp2Jc-VffSEsYEKjh13mcM
"""

from google.colab import files
import pandas as pd

uploaded = files.upload()

data3 = data_theo[['Name', 'Sex', 'Age', 'Pclass', 'Fare']]
penumpang = data3.groupby('Sex') ['Name'].nunique()
print('Jumlah Penumpang: \n', penumpang)

#memanggil dan menampilkan dataset
data_theo = pd.read_csv('/content/titanic.csv.csv')
print(data_theo)

#mengambil data pada kolom tertentu
data1 = data_theo.loc[:,['Age','Pclass','Survived']]
print(data1)

#memvisualisasikan data titanic
data2 = data_theo[['Age', 'Pclass', 'Survived']]
data2.plot(title='Persebaran Data', x='Age', y='Pclass', kind='scatter', c='Survived', colormap='Paired')

data4 = data_theo[['Name', 'Sex', 'Age', 'Pclass', 'Fare']]
notsurvivedpassanger=data4['Sex'].loc[data_theo['Survived']==0]
print('Penumpang yang tidak survived:\n',
notsurvivedpassanger.value_counts())
survivedpassanger=data4['Sex'].loc[data_theo['Survived']==1]
print('\nPenumpang yang survived:\n',
survivedpassanger.value_counts())

#memanipulasi data jumlah penumpang berdasarkan group Pclass
data3 = data_theo[['Name', 'Sex', 'Age', 'Pclass', 'Fare']]
penumpang=data3.groupby('Sex')['Name'].nunique()
print('Jumlah Penumpang:\n', penumpang)

#memfilter data penumpang yang selamat berdasarkan pclass
data4 = data_theo[['Name', 'Sex', 'Age', 'Pclass', 'Fare']]
notsurvivedpassanger=data4['Pclass'].loc[data_theo['Survived']==0]
print('Penumpang yang tidak survived:\n', notsurvivedpassanger.value_counts())
survivedpassanger=data4['Pclass'].loc[data_theo['Survived']==1]
print('\nPenumpang yang survived:\n', survivedpassanger.value_counts())